/**
 * voice-report.ts
 *
 * Generates a Markdown voice report and prints it to stdout.
 * Used by voice-report.yml to push to the GitHub Wiki.
 *
 * Usage:
 *   tsx --env-file=.env.local scripts/voice-report.ts > /tmp/voice-report.md
 */

import { loadConfig } from '../src/config/loader.js';
import { SqliteStorage } from '../src/voice/sqlite-storage.js';
import { SupabaseStorage } from '../src/voice/supabase-storage.js';
import type { IVoiceStorage, VoicePost } from '../src/voice/storage.js';

function bar(value: number, max = 1.0, width = 10): string {
  const filled = Math.round((value / max) * width);
  return '█'.repeat(filled) + '░'.repeat(width - filled);
}

function fmt(n: number | null, decimals = 2): string {
  return n !== null ? n.toFixed(decimals) : '—';
}

function fmtDate(iso: string | null): string {
  if (!iso) return '—';
  return new Date(iso).toLocaleDateString('es-CL', { day: '2-digit', month: '2-digit', year: '2-digit' });
}

function statsBlock(posts: VoicePost[]): string {
  const published = posts.length;
  const withRatio = posts.filter((p) => p.edit_ratio !== null);
  const avgRatio = withRatio.length
    ? withRatio.reduce((s, p) => s + (p.edit_ratio ?? 0), 0) / withRatio.length
    : null;
  const withEngagement = posts.filter((p) => p.engagement_score !== null);
  const avgEngagement = withEngagement.length
    ? withEngagement.reduce((s, p) => s + (p.engagement_score ?? 0), 0) / withEngagement.length
    : null;

  const sevenDaysAgo = Date.now() - 7 * 24 * 60 * 60 * 1000;
  const lastWeek = posts.filter(
    (p) => p.published_at && new Date(p.published_at).getTime() > sevenDaysAgo,
  ).length;

  const lines = [
    '## Summary',
    '',
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Published posts (last 30) | ${published} |`,
    `| Posts last 7 days | ${lastWeek} |`,
    `| Avg edit_ratio | ${avgRatio !== null ? `${fmt(avgRatio)} ${bar(avgRatio)}` : '—'} |`,
    `| Avg engagement_score | ${avgEngagement !== null ? `${fmt(avgEngagement)} ${bar(avgEngagement)}` : '— (no data yet)' } |`,
    '',
  ];
  return lines.join('\n');
}

function postsTable(posts: VoicePost[]): string {
  const header = [
    '## Recent Posts',
    '',
    '| Date | Repo | Platform | Finding | edit_ratio | reactions | engagement |',
    '|------|------|----------|---------|-----------|-----------|------------|',
  ];

  const rows = posts.map((p) => {
    const finding = (p.top_finding ?? '—').slice(0, 40);
    const repo = p.repo.split('/')[1] ?? p.repo;
    return `| ${fmtDate(p.published_at)} | ${repo} | ${p.platform} | ${finding} | ${fmt(p.edit_ratio)} | ${p.reactions_count > 0 ? p.reactions_count : '—'} | ${fmt(p.engagement_score)} |`;
  });

  return [...header, ...rows, ''].join('\n');
}

async function main(): Promise<void> {
  const config = loadConfig();

  const storage: IVoiceStorage = process.env['SUPABASE_URL']
    ? new SupabaseStorage(process.env['SUPABASE_URL'], process.env['SUPABASE_SERVICE_ROLE_KEY'] ?? '')
    : new SqliteStorage(process.env['SQLITE_PATH'] ?? 'data/devcast.db');

  const posts = await storage.getRecentPublished(30);

  const now = new Date().toLocaleString('es-CL', {
    timeZone: config.scheduling.timezone,
    dateStyle: 'full',
    timeStyle: 'short',
  });

  const report = [
    `# Voice Report`,
    '',
    `_Updated: ${now} (${config.scheduling.timezone})_`,
    '',
    statsBlock(posts),
    postsTable(posts),
    '---',
    '_Generated by [devcast](https://github.com/vialabs-net/social-engagement)_',
  ].join('\n');

  process.stdout.write(report);
}

main().catch((err) => {
  process.stderr.write(`voice-report failed: ${String(err)}\n`);
  process.exit(1);
});
